"""
Colors
"""
WHITE = 'WHITE'
BLACK = 'BLACK'
RED = 'RED'
GREEN = 'GREEN'
AMBER = 'AMBER'
BLUE = 'BLUE'
TREND = 'TREND'
GREY = 'GREY'
DARK_BLUE = 'DARK_BLUE'
AQUA = 'AQUA'

"""
Fonts
"""
DEJAVU_SANS = 'DejaVuSans'
DEJAVU_SANS_BOLD = 'DejaVuSans-Bold'
DEJAVU_SANS_MONO = 'DejaVuSansMono'
DEJAVU_SANS_MONO_BOLD = 'DejaVuSansMono-Bold'
DEJAVU_SERIF = 'DejaVuSerif'
DEJAVU_SERIF_BOLD = 'DejaVuSerif-Bold'
DEJAVU_SERIF_CONDENSED = 'DejaVuSerifCondensed'
DEJAVU_SERIF_CONDENSED_BOLD = 'DejaVuSerifCondensed-Bold'
LUCIDA_SANS = 'LucidaSans'

"""
Template Column Names
"""
CURRENT_YEAR_DATA = 'CurrentYearData'
CURRENT_YEAR_MEASURES = 'CurrentYearMeasures'
PMT_ADDITIONAL_DATA = 'PMTAdditionalData'

"""
Measure TYPES
"""
CPM = 'CPM'
SDM = 'SDM'
SSG = 'SSG'
# used by templates that are not related to
# measure data sources
UNKNOWN = 'UNKNOWN'

"""
Template column names
"""
FISCAL_YEAR = 'FISCAL_YEAR'
MEASURE_ID = 'MEASURE_ID'
MEASURE_REF_NO = 'MEASURE_REF_NO'
MEASURE_TYPE = 'MEASURE_TYPE'
OUTCOME = 'OUTCOME'
PRIORITY = 'PRIORITY'
MEASURE_TITLE = 'MEASURE_TITLE'
MEASURE_DESCRIPTION = 'MEASURE_DESCRIPTION'
ADDITIONAL_KPI_INFO = 'ADDITIONAL_KPI_INFORMATION'
NEW_EXISTING = 'NEW_EXISTING'
PREFERRED_DOT = 'PREFERRED_DIRECTION_OF_TRAVEL'
AIM = 'AIM'
FREQUENCY_MONTHLY_QUARTERLY_1_2_YEARLY_ANNUAL = 'FREQUENCY_MONTHLY_QUARTERLY_1_2_YEARLY_ANNUAL'
DATA_FORMAT = 'DATA_FORMAT'
DATA_PRESENTED = 'DATA_PRESENTED'
BASELINE = 'BASELINE'
TOLERANCES = 'TOLERANCES'
DIRECTORATE = 'DIRECTORATE'
CABINET_MEMBER_PORTFOLIO = 'CABINET_MEMBER_PORTFOLIO'
CORPORATE_DIRECTOR = 'CORPORATE_DIRECTOR'
RESPONSIBLE_OFFICER = 'RESPONSIBLE_OFFICER'
MEASURE_OWNER = 'MEASURE_OWNER'
DATA_SOURCE = 'DATA_SOURCE'
EXPECTED_AVAILABILITY = 'EXPECTED_DATE_MONTH_AVAILABILITY'
FINAL_DQAF_RECEIVED = 'FINAL_DQAF_RECEIVED'
OUTCOME_NO = 'OUTCOME_NO'
OUTCOME_PRIORITY_NO = 'OUTCOME_PRIORITY_NO'
THEME = 'THEME'
THEME_PRIORITY_NO = 'THEME_PRIORITY_NO'
FREQUENCY = 'FREQUENCY'
QUARTER = 'QUARTER'
MONTH = 'MONTH'
RESULT = 'RESULT'
TARGET = 'TARGET'
PERFORMANCE = 'PERFORMANCE'
VARIANCE_FROM_TARGET = 'VARIANCE_FROM_TARGET'
DOT_FROM_PREVIOUS_MONTH = 'DOT_FROM_PREVIOUS_MONTH'
DOT_FROM_PREVIOUS_QUARTER = 'DOT_FROM_PREVIOUS_QUARTER'
DOT_FROM_SAME_PERIOD_LAST_YEAR = 'DOT_FROM_SAME_PERIOD_LAST_YEAR'
STATUS_PROVISIONAL_CONFIRMED = 'STATUS_PROVISIONAL_CONFIRMED'
DIRECTORATE_COMMENTARY = 'DIRECTORATE_COMMENTARY'
REPORT_COMMENTARY = 'REPORT_COMMENTARY'
BENCHMARKABLE_NATIONALLY = 'BENCHMARKABLE_NATIONALLY'
BENCHMARK_RESULT = 'BENCHMARK_RESULT'
BENCHMARK_GROUP_FOR_REPORTING_PURPOSES = 'BENCHMARK_GROUP_FOR_REPORTING_PURPOSES'
BIRMINGHAM_RESULT_AT_TIME_OF_BENCHMARK = 'BIRMINGHAM_RESULT_AT_TIME_OF_BENCHMARK'
BIRMINGHAM_QUARTILE_POSITION = 'BIRMINGHAM_QUARTILE_POSITION'
YEAR_OF_BENCHMARK_DATA = 'YEAR_OF_BENCHMARK_DATA'
REASON_FOR_NON_NATIONAL_BENCHMARK_IF_RELEVANT = 'REASON_FOR_NON_NATIONAL_BENCHMARK_IF_RELEVANT'
QUARTILE_PROJECTION = 'QUARTILE_PROJECTION'
ASSISTANT_DIRECTOR_SIGN_OFF = 'ASSISTANT_DIRECTOR_SIGN_OFF'
DMT_SIGN_OFF_DATE = 'DMT_SIGN_OFF_DATE'
CABINET_MEMBERS_SIGN_OFF_DATE = 'CABINET_MEMBERS_SIGN_OFF_DATE'
YEAR = 'YEAR'
YEAR_MONTH = 'YEAR_MONTH'
YEAR_QUARTER = 'YEAR_QUARTER'
MEASURE_TEXT_COLUMN_1 = 'MEASURE_TEXT_COLUMN1'
MEASURE_TEXT_COLUMN_2 = 'MEASURE_TEXT_COLUMN2'
MEASURE = 'MEASURE'

"""
Application constants
"""
REPORT_NAME = 'Performance Monitoring Report'
REPORT_ENCODING = 'utf-8'
REPORT_FONT = DEJAVU_SERIF_CONDENSED
EXT_PDF = 'pdf'
MAX_FORMATTED_VALUE_SIZE = 14
NAN = 'nan'
FREQ_ANNUAL = 'A'
FREQ_QUARTER = 'Q'
FREQ_MONTHLY = 'M'
DOTS = ["p", "q", "r", "s", "u"]

PERF_BLUE = 'BLUE'
PERF_RED = 'RED'
PERF_AMBER = 'AMBER'
PERF_GREEN = 'GREEN'
PERF_NYD = 'NYD'
PERF_AWAITING = 'AWAITING'
PERF_TREND = 'TREND'
PERF_PREV_REPORTED = 'PREVIOUSLY_REPORTED'

OUTCOME_LEAN_WORK_INVEST = 'Birmingham is an entrepreneurial city to learn, work and invest in'
OUTCOME_GROW_UP = 'Birmingham is an aspirational city to grow up in'
OUTCOME_CWG = 'Birmingham residents gain the maximum benefit from hosting the Commonwealth Games'
OUTCOME_AGE_WELL = 'Birmingham is a fulfilling city to age well in'
OUTCOME_SSG = 'Support Services and Governance'
OUTCOME_LIVE_IN = 'Birmingham is a great city to live in'

ROOT = 'ROOT'
TEMP = 'TEMP'
RESOURCES = 'RESOURCES'
LOG = 'LOG'
TEMPLATES = 'TEMPLATES'
OUTPUT = 'OUTPUT'

"""
Image file names
"""
LEGEND = 'LEGEND'
OFSTED = 'OFSTED'
RISK_MAP = 'RISK_MAP'
WORKFORCE_EXPENDITURE = 'WORKFORCE_EXPENDITURE'
SCHOOLS_IN_DEFICIT = 'SCHOOLS_IN_DEFICIT'
FINAL_AUDIT_REPORT = 'FINAL_AUDIT_REPORT'
