"""
Colors
"""
WHITE = 'WHITE'
BLACK = 'BLACK'
RED = 'RED'
GREEN = 'GREEN'
AMBER = 'AMBER'
BLUE = 'BLUE'
TREND = 'TREND'
GREY = 'GREY'
DARK_BLUE = 'DARK_BLUE'
AQUA = 'AQUA'
LIGHT_AQUA = 'LIGHT_AQUA'

"""
Fonts
"""
DEJAVU_SANS = 'DejaVuSans'
DEJAVU_SANS_BOLD = 'DejaVuSans-Bold'
DEJAVU_SANS_MONO = 'DejaVuSansMono'
DEJAVU_SANS_MONO_BOLD = 'DejaVuSansMono-Bold'
DEJAVU_SERIF = 'DejaVuSerif'
DEJAVU_SERIF_BOLD = 'DejaVuSerif-Bold'
DEJAVU_SERIF_CONDENSED = 'DejaVuSerifCondensed'
DEJAVU_SERIF_CONDENSED_BOLD = 'DejaVuSerifCondensed-Bold'
LUCIDA_SANS = 'LucidaSans'

"""
Template Column Names
"""
CURRENT_YEAR_DATA = 'CurrentYearData'
CURRENT_YEAR_MEASURES = 'CurrentYearMeasures'
PMT_ADDITIONAL_DATA = 'PMTAdditionalData'
HR_SCORECARD_DATA = 'HRScorecardData'
HR_ABSENCES_DATA = 'HRAbsencesData'
HR_SICKNESS_DATA = 'HRSicknessData'
HR_TRAINING_DATA = 'HRTrainingData'
DCS_COMPLAINTS_DATA = 'DCSComplaintsData'

"""
Measure TYPES
"""
CPM = 'CPM'
SDM = 'SDM'
SSG = 'SSG'
# used by PMT related templates
PMT_ADDITIONAL = 'PMT_ADDITIONAL'
# used by HR related templates
HR_SCORECARD = 'HR_SCORECARD'
HR_ABSENCES = 'HR_ABSENCES'
HR_SICKNESS = 'HR_SICKNESS'
HR_TRAINING = 'HR_TRAINING'
DCS_COMPLAINTS = 'DCS_COMPLAINTS'

"""
Template column names
"""
FISCAL_YEAR = 'FISCAL_YEAR'
MEASURE_ID = 'MEASURE_ID'
MEASURE_REF_NO = 'MEASURE_REF_NO'
MEASURE_TYPE = 'MEASURE_TYPE'
OUTCOME = 'OUTCOME'
PRIORITY = 'PRIORITY'
MEASURE_TITLE = 'MEASURE_TITLE'
MEASURE_DESCRIPTION = 'MEASURE_DESCRIPTION'
ADDITIONAL_KPI_INFO = 'ADDITIONAL_KPI_INFORMATION'
NEW_EXISTING = 'NEW_EXISTING'
PREFERRED_DOT = 'PREFERRED_DIRECTION_OF_TRAVEL'
AIM = 'AIM'
FREQUENCY_MONTHLY_QUARTERLY_1_2_YEARLY_ANNUAL = 'FREQUENCY_MONTHLY_QUARTERLY_1_2_YEARLY_ANNUAL'
DATA_FORMAT = 'DATA_FORMAT'
DATA_PRESENTED = 'DATA_PRESENTED'
BASELINE = 'BASELINE'
TOLERANCES = 'TOLERANCES'
DIRECTORATE = 'DIRECTORATE'
CABINET_MEMBER_PORTFOLIO = 'CABINET_MEMBER_PORTFOLIO'
CORPORATE_DIRECTOR = 'CORPORATE_DIRECTOR'
RESPONSIBLE_OFFICER = 'RESPONSIBLE_OFFICER'
MEASURE_OWNER = 'MEASURE_OWNER'
DATA_SOURCE = 'DATA_SOURCE'
EXPECTED_AVAILABILITY = 'EXPECTED_DATE_MONTH_AVAILABILITY'
FINAL_DQAF_RECEIVED = 'FINAL_DQAF_RECEIVED'
OUTCOME_NO = 'OUTCOME_NO'
OUTCOME_PRIORITY_NO = 'OUTCOME_PRIORITY_NO'
THEME = 'THEME'
THEME_PRIORITY_NO = 'THEME_PRIORITY_NO'
FREQUENCY = 'FREQUENCY'
QUARTER = 'QUARTER'
MONTH = 'MONTH'
RESULT = 'RESULT'
TARGET = 'TARGET'
PERFORMANCE = 'PERFORMANCE'
VARIANCE_FROM_TARGET = 'VARIANCE_FROM_TARGET'
DOT_FROM_PREVIOUS_MONTH = 'DOT_FROM_PREVIOUS_MONTH'
DOT_FROM_PREVIOUS_QUARTER = 'DOT_FROM_PREVIOUS_QUARTER'
DOT_FROM_SAME_PERIOD_LAST_YEAR = 'DOT_FROM_SAME_PERIOD_LAST_YEAR'
STATUS_PROVISIONAL_CONFIRMED = 'STATUS_PROVISIONAL_CONFIRMED'
DIRECTORATE_COMMENTARY = 'DIRECTORATE_COMMENTARY'
REPORT_COMMENTARY = 'REPORT_COMMENTARY'
BENCHMARKABLE_NATIONALLY = 'BENCHMARKABLE_NATIONALLY'
BENCHMARK_RESULT = 'BENCHMARK_RESULT'
BENCHMARK_GROUP_FOR_REPORTING_PURPOSES = 'BENCHMARK_GROUP_FOR_REPORTING_PURPOSES'
BIRMINGHAM_RESULT_AT_TIME_OF_BENCHMARK = 'BIRMINGHAM_RESULT_AT_TIME_OF_BENCHMARK'
BIRMINGHAM_QUARTILE_POSITION = 'BIRMINGHAM_QUARTILE_POSITION'
YEAR_OF_BENCHMARK_DATA = 'YEAR_OF_BENCHMARK_DATA'
REASON_FOR_NON_NATIONAL_BENCHMARK_IF_RELEVANT = 'REASON_FOR_NON_NATIONAL_BENCHMARK_IF_RELEVANT'
QUARTILE_PROJECTION = 'QUARTILE_PROJECTION'
ASSISTANT_DIRECTOR_SIGN_OFF = 'ASSISTANT_DIRECTOR_SIGN_OFF'
DMT_SIGN_OFF_DATE = 'DMT_SIGN_OFF_DATE'
CABINET_MEMBERS_SIGN_OFF_DATE = 'CABINET_MEMBERS_SIGN_OFF_DATE'
YEAR = 'YEAR'
YEAR_MONTH = 'YEAR_MONTH'
YEAR_QUARTER = 'YEAR_QUARTER'
MEASURE_TEXT_COLUMN_1 = 'MEASURE_TEXT_COLUMN1'
MEASURE_TEXT_COLUMN_2 = 'MEASURE_TEXT_COLUMN2'
MEASURE = 'MEASURE'
ADULTS_SOCIAL_CARE = 'ADULTS_SOCIAL_CARE'
EDUCATION_AND_SKILLS = 'EDUCATION_AND_SKILLS'
INCLUSIVE_GROWTH = 'INCLUSIVE_GROWTH'
FINANCE_AND_GOVERNANCE = 'FINANCE_AND_GOVERNANCE'
NEIGHBOURHOODS = 'NEIGHBOURHOODS'
PARTNERSHIPS_INSIGHT_AND_PREVENTION = 'PARTNERSHIPS_INSIGHT_AND_PREVENTION'
DIGITAL_AND_CUSTOMER_SERVICES = 'DIGITAL_AND_CUSTOMER_SERVICES'
HR_AND_ORGANISATION_DEVELOPMENT = 'HR_AND_ORGANISATION_DEVELOPMENT'
BIRMINGHAM_CITY_COUNCIL = 'BIRMINGHAM_CITY_COUNCIL'
COMMONWEALTH_GAMES = 'COMMONWEALTH_GAMES'
PERCENTAGE = 'PERCENTAGE'
DATE_OF_DATA = 'DATE_OF_DATA'
TOTAL = 'TOTAL'
BIRMINGHAM_CHILDRENS_TRUST = 'BIRMINGHAM_CHILDRENS_TRUST'
UNASSIGNED = 'UNASSIGNED'

"""
Application constants
"""
REPORT_NAME = 'Performance Monitoring Report'
REPORT_ENCODING = 'utf-8'
REPORT_FONT = DEJAVU_SERIF_CONDENSED
EXT_PDF = 'pdf'
MAX_FORMATTED_VALUE_SIZE = 14
NAN = 'nan'
FREQ_ANNUAL = 'A'
FREQ_QUARTER = 'Q'
FREQ_MONTHLY = 'M'
DOTS = ["p", "q", "r", "s", "u"]
FISCAL_MONTHS = {
    1: 'APR',
    2: 'MAY',
    3: 'JUN',
    4: 'JUL',
    5: 'AUG',
    6: 'SEP',
    7: 'OCT',
    8: 'NOV',
    9: 'DEC',
    10: 'JAN',
    11: 'FEB',
    12: 'MAR'
}
QUARTERS = ['Q1', 'Q2', 'Q3', 'Q4']
QUARTER_MONTH_MAPPING = {
    QUARTERS[0]: list(FISCAL_MONTHS.values())[:3],
    QUARTERS[1]: list(FISCAL_MONTHS.values())[3:6],
    QUARTERS[2]: list(FISCAL_MONTHS.values())[6:9],
    QUARTERS[3]: list(FISCAL_MONTHS.values())[9:]
}

PERF_BLUE = 'BLUE'
PERF_RED = 'RED'
PERF_AMBER = 'AMBER'
PERF_GREEN = 'GREEN'
PERF_NYD = 'NYD'
PERF_AWAITING = 'AWAITING'
PERF_TREND = 'TREND'
PERF_PREV_REPORTED = 'PREVIOUSLY_REPORTED'

OUTCOME_LEARN_WORK_INVEST = 'BIRMINGHAM_IS_AN_ENTREPRENEURIAL_CITY_TO_LEARN_WORK_AND_INVEST_IN'
OUTCOME_GROW_UP = 'BIRMINGHAM_IS_AN_ASPIRATIONAL_CITY_TO_GROW_UP_IN'
OUTCOME_CWG = 'BIRMINGHAM_RESIDENTS_GAIN_THE_MAXIMUM_BENEFIT_FROM_HOSTING_THE_COMMONWEALTH_GAMES'
OUTCOME_AGE_WELL = 'BIRMINGHAM_IS_A_FULFILLING_CITY_TO_AGE_WELL_IN'
OUTCOME_SSG = 'SUPPORT_SERVICES_AND_GOVERNANCE'
OUTCOME_LIVE_IN = 'BIRMINGHAM_IS_A_GREAT_CITY_TO_LIVE_IN'

ROOT = 'ROOT'
TEMP = 'TEMP'
RESOURCES = 'RESOURCES'
LOG = 'LOG'
TEMPLATES = 'TEMPLATES'
OUTPUT = 'OUTPUT'
RESOURCES_FONTS = 'RESOURCES_FONTS'

"""
Image file names
"""
LEGEND = 'LEGEND'
OFSTED = 'OFSTED'
RISK_MAP = 'RISK_MAP'
WORKFORCE_EXPENDITURE = 'WORKFORCE_EXPENDITURE'
SCHOOLS_IN_DEFICIT = 'SCHOOLS_IN_DEFICIT'
FINAL_AUDIT_REPORT = 'FINAL_AUDIT_REPORT'
